import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>HN Offline</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="font-bold mx-auto max-w-lg">HN Client</div>
      </main>
    </>
  );
}
